### PR TITLE
Pyppeteer 0.2.2

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- builds on #2
- adds version pins for many of the dependencies from the [upstream](https://github.com/pyppeteer/pyppeteer/blob/dev/pyproject.toml)
- `pip check`
- removes the patch
  - probably needs investigation
- adds self as a co-maintainer

### CODE REVIEW

**Comment by kiwi0fruit** [comment]
This new version removes necessary patch. In particualr a patch that maked download secure. It's a bad idea to reduce security of the conda package. I guess it's better to update the patch.

**Comment by kiwi0fruit** [comment]
In particular it's this PR that was never pulled https://github.com/miyakogi/pyppeteer/pull/189

**Comment by bollwyvl** [comment]
Agreed on shipping the best thing we know how to! Pyppeteer and its primary
fork merged: the new org may be more responsive if the path was
resubmitted, provided it hasn't been included: they've been fairly active.
I'll do some archaeology.

**Comment by kiwi0fruit** [comment]
I've checked - the PR wasn't added to the new version. And it's actually pretty easy to patch for secure download. It simply need me or somebody to generate a new patch (the very same changes but maybe on other lines).

**Comment by bollwyvl** [comment]
Right, but getting it upstreamed is preferable from a maintenance point of
view...

**Comment by bollwyvl** [comment]
Yeah, they have it here, on this unreleased branch:

https://github.com/pyppeteer/pyppeteer/blob/pup2.1.1/pyppeteer/browser_fetcher.py

Perhaps just wait and ship that when it comes out.

https://github.com/pyppeteer/pyppeteer/projects/3

**Comment by kiwi0fruit** [comment]
Yeah. Wait for newer version is the best option.

**Comment by SylvainCorlay** [comment]
@kiwi0fruit would be interested in re-introducing the secure download patch that was removed in the PR so that we can include this new version?

**Comment by SylvainCorlay** [comment]
I opened #5 which seems to work.

**Pull request closed without merging**
